[package]
name = "uefi"
version = "0.1.0"
authors = ["Aurora Berta-Oldham"]
edition = "2018"

[dependencies]
enums = { path = "../enums" }
ucs2 = { path = "../ucs2" }
io = { path = "../io", features = [ "no-std", "alloc-impl" ] }
memory = { path = "../memory" }
acpi = { path = "../acpi" }
