[package]
name = "io"
version = "0.1.0"
authors = ["Todd <16536474+ToddBertaOldham@users.noreply.github.com>"]
edition = "2018"

[features]
alloc-impl = []
no-std = []

[dependencies]
memory = { path = "../memory" }