[workspace]

members = [
    "boot/uefi/core",
    "boot/uefi/loader",
    "kernel",
    "shared/elf",
    "shared/generation",
    "shared/arch/x86",
    "shared/bits",
    "shared/io",
    "shared/uart_8250_family"
]