[package]
name = "uart_8250_family"
version = "0.1.0"
authors = ["Aurora Berta-Oldham"]
edition = "2018"

[dependencies]
x86 = { path = "../arch/x86" }
io = { path = "../io", features = [ "no-std" ] }
enums = { path = "../enums" }
memory = { path = "../memory" }
