// *************************************************************************
// ELF.h
// Copyright 2018 Todd Berta-Oldham
// This code is licensed under MIT.
// *************************************************************************

#ifndef PET_COMMON_ELF_HEADER
#define PET_COMMON_ELF_HEADER

#include <stdint.h>

#define ELFMAGIC0 0x7F
#define ELFMAGIC1 0x45
#define ELFMAGIC2 0x4C
#define ELFMAGIC3 0x46

#define ELFCLASS_32BIT 1
#define ELFCLASS_64BIT 2

#define ELFDATA_NONE 0
#define ELFDATA_2LSB 1
#define ELFDATA_2MSB 2 

#define ELFOSABI_SYSTEMV 0x0
#define ELFOSABI_HP_UX 0x1
#define ELFOSABI_NETBSD 0x2
#define ELFOSABI_LINUX 0x3
#define ELFOSABI_GNUHURD 0x4
#define ELFOSABI_SOLARIS 0x6
#define ELFOSABI_AIX 0x7
#define ELFOSABI_IRIX 0x8
#define ELFOSABI_FREEBSD 0x9
#define ELFOSABI_TRU64 0xA
#define ELFOSABI_NOVELLMODESTO 0xB
#define ELFOSABI_OPENBSD 0xC
#define ELFOSABI_OPENVMS 0xD
#define ELFOSABI_NONSTOPKERNEL 0xE
#define ELFOSABI_AROS 0xF
#define ELFOSABI_FENIXOS 0x10
#define ELFOSABI_CLOUDABI 0x11

struct ELFIdentificationHeader
{
    uint8_t Magic0;
    uint8_t Magic1;
    uint8_t Magic2;
    uint8_t Magic3;
    uint8_t Class;
    uint8_t Data;
    uint8_t Version;
    uint8_t OSABI;
    uint8_t ABIVersion;
    uint8_t Unused[7];
};

#define ELFOBJECTTYPE_RELOCATABLE 1
#define ELFOBJECTTYPE_EXECUTABLE 2
#define ELFOBJECTTYPE_SHARED 3
#define ELFOBJECTTYPE_CORE 4

#define ELFARCHITECTURE_NONE 0x0
#define ELFARCHITECTURE_SPARC 0x2
#define ELFARCHITECTURE_X86 0x3
#define ELFARCHITECTURE_MIPS 0x8
#define ELFARCHITECTURE_POWERPC 0x14
#define ELFARCHITECTURE_S390 0x16
#define ELFARCHITECTURE_ARM 0x28
#define ELFARCHITECTURE_SUPERH 0x2A
#define ELFARCHITECTURE_AI_64 0x32
#define ELFARCHITECTURE_X86_64 0x3E
#define ELFARCHITECTURE_AARCH64 0xB7

#define ELFPROGRAMHEADERTYPE_NULL 0
#define ELFPROGRAMHEADERTYPE_LOAD 1
#define ELFPROGRAMHEADERTYPE_DYNAMIC 2
#define ELFPROGRAMHEADERTYPE_INTERPRETER 3
#define ELFPROGRAMHEADERTYPE_NOTE 4

#define ELFSECTIONHEADERTYPE_NULL 0
#define ELFSECTIONHEADERTYPE_PROGRAMBITS 1
#define ELFSECTIONHEADERTYPE_SYMBOLTABLE 2
#define ELFSECTIONHEADERTYPE_STRINGTABLE 3
#define ELFSECTIONHEADERTYPE_RELOCATION 4
#define ELFSECTIONHEADERTYPE_HASH 5
#define ELFSECTIONHEADERTYPE_DYNAMIC 6
#define ELFSECTIONHEADERTYPE_NOTE 7
#define ELFSECTIONHEADERTYPE_NOBITS 8
#define ELFSECTIONHEADERTYPE_RELOCATABLE 9

#endif