[package]
name = "uefi_loader"
version = "0.1.0"
authors = ["Aurora Berta-Oldham"]
edition = "2018"

[dependencies]
uefi_core = { path = "../core" }
elf = { path = "../../../shared/elf" }
x86 = { path = "../../../shared/arch/x86" }
kernel_init = { path = "../../../shared/kernel/init/" }