[package]
name = "kernel_init"
version = "0.1.0"
authors = ["Aurora Berta-Oldham"]
edition = "2018"

[dependencies]
uart_8250_family = { path = "../../uart_8250_family/" }
memory = { path = "../../memory/" }
acpi = { path = "../../acpi/" }