[package]
name = "x86"
version = "0.1.0"
authors = ["Aurora Berta-Oldham"]
edition = "2018"

[dependencies]
bits = { path = "../../bits/" }
memory = { path = "../../memory/" }
enums = { path = "../../enums/" }